### ISSUE TITLE
Parsing variant name from VCF ID column

### ISSUE THREAD

**Issue by songtaogui** [UofS-Pulse-Binfo/vcf_genotypes#38]
Hi, 
I was trying to load genotypes from vcf file. However, instead of using the raw IDs in the vcf file, the loaded variants were renamed by the position info in the vcf file, such as `chr1p29143`. 

How to name the variant by its real ID while loading from a vcf file?

Thank you.
Best wishes,

Songtao Gui

**Comment by carolyncaron** [comment]
Thanks for your question!

It looks like I had this on my to-do list for a while:

https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/26f7482bc29a531a2eab386810e3ce4cf2c3b4ee/includes/genotypes_loader.vcf.inc#L116 

The loader combines the CHROM and POS values since I normally deal with VCF files that do not contain IDs, and this is sadly not configurable which I think would be the most optimal solution. Your suggestion is really easy to implement though, so I will update the module to prioritize the ID as the variant name and instead use my current implementation as a backup.

**Comment by songtaogui** [comment]
Thank you for your reply and looking forward to the updating.

I would try to use the tab-delimited data file to upload my data first.

Best wishes.

**Comment by songtaogui** [comment]
Hi, @carolyncaron 
I was trying to upload genotype data through tsv format, but I got errors like "There is no genotype call to print to myfile.tsv" when using both Genotype Matrix format and Genotype Flat-file. I have checked that this error message was generated from the [`genotypes_loader_helper_copy_records function` ](https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/26f7482bc29a531a2eab386810e3ce4cf2c3b4ee/api/genotypes_loader.api.inc#L154) ,which was only used in the vcf loader script [genotypes_loader.vcf.inc](https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/94741e18042467b5c941060267a83a328364fe1f/includes/genotypes_loader.vcf.inc). 

It seems that the genotype loader takes my input tsv file as vcf inputs, did I miss something? I have successfully uploaded the same data using vcf files before, so it may not be the data's problem.

My upload command is 

```bash
# input.tsv may be in Genotype Matrix format and Genotype Flat-file format
drush load-genotypes input.tsv samples.list --organism="Zea mays:cultivar B73" --variant-type="SNP" --marker-type="genetic_marker" --project-name="test SNP" --ndgeolocation="here"
```

And the input.tsv were formated like: 

**Genotype Matrix**:

Marker name |Chromosome|Position|CIMBL32|CIMBL89|CIMBL7|CIMBL45X|ZHENG58|CML415|CIMBL46
:-----------|:---------|:-------|:------|:------|:-----|:-------|:------|:-----|:------
chr1.s_2354 |1         |2354    |GG     |AA     |AA    |AA      |AA     |AA    |AA
chr1.s_2356 |1         |2356    |CC     |TT     |CT    |CC      |TT     |TT    |TT
chr1.s_16124|1         |16124   |GG     |GG     |GG    |GG      |GG     |GG    |GG
chr1.s_19179|1         |19179   |TT     |TT     |TT    |TT      |TT     |TT    |TT
chr1.s_19431|1         |19431   |GG     |GG     |GG    |GG      |GG     |GG    |GG
chr1.s_19617|1         |19617   |CC     |CC     |CC    |CC      |CC     |CC    |CC
chr1.s_19676|1         |19676   |GG     |GG     |GG    |GG      |GG     |GG    |GG
chr1.s_19724|1         |19724   |GG     |GG     |GG    |GG      |GG     |GG    |GG
chr1.s_20415|1         |20415   |CC     |CC     |CC    |CC      |CC     |CC    |CC

**Genotype Flat-file**:

Marker name|Chromosome|Position|Sample name|Genotype call
:----------|:---------|:-------|:----------|:------------
chr1.s_2354|1         |2354    |CIMBL32    |GG
chr1.s_2354|1         |2354    |CIMBL89    |AA
chr1.s_2354|1         |2354    |CIMBL7     |AA
chr1.s_2354|1         |2354    |CIMBL45X   |AA
chr1.s_2354|1         |2354    |ZHENG58    |AA
chr1.s_2354|1         |2354    |CML415     |AA
chr1.s_2354|1         |2354    |CIMBL46    |AA
chr1.s_2354|1         |2354    |CIMBL70    |AA
chr1.s_2354|1         |2354    |CIMBL124   |AA

**Comment by carolyncaron** [comment]
Admittedly I haven't been diligent in testing the matrix or flat-file formats since introducing the copy method for VCF files (we have a backlog of VCF files to insert so this has been my priority). The VCF function is significantly faster than those 2 options because of this. It is really odd that you are seeing an error from the copy records function for the other formats. Could you create a new issue for this and copy and paste the error message that you get?

My change for setting the variant name to the ID field from VCF is pending review. I would suggest you wait for this change to be merged in and then load from VCF since this has had more extensive testing than the other two file formats. Thanks again for bringing this to my attention!

**Comment by laceysanderson** [comment]
> My change for setting the variant name to the ID field from VCF is pending review. I would suggest you wait for this change to be merged in and then load from VCF since this has had more extensive testing than the other two file formats. Thanks again for bringing this to my attention!

@songtaogui the PR referenced has been merged! Let us know if this fixes your problem :-)

**Comment by songtaogui** [comment]
@laceysanderson @carolyncaron  yes, it works. Thank you.
