### ISSUE TITLE
Improve speed via COPY method

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/vcf_genotypes#4]
The fastest method I've found for loading large files is to use [PostgreSQL COPY FROM command](https://www.postgresql.org/docs/9.2/static/sql-copy.html). However, this query cannot be executed via chado_query() because it would require the database user to have superuser privileges which would in turn be a security issue. In order to safely get around this, we take advantage of the fact that the file is local (must be transferred separately due to size) and use the command line \copy variation of this command. 

Here's an example of how to execute the \copy command: https://github.com/UofS-Pulse-Binfo/generate_trpdata/blob/master/api/generate.genotypes.api.inc#L498. 

To use the \copy from command you need to have first generated a file with your data. You can do this by modifying the helper function (https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/master/api/genotypes_loader.api.inc#L25) to check if the mode is insert only and if so write to a file instead of executing the insert command. Then at the end of the function check the number of lines and if it exceeds a set number (e.g. 10,000): (1) create the copy from command, (2) execute it and (3) empty the file. You would need an additional API function to copy in all the partial files at the end.

**Comment by laceysanderson** [comment]
Here's a quick, untested helper function that should do what you want. Notice the two @todo's which might need further thought/optimization.

```php
/**
 * Adds/Selects a record based on the mode. Helper function for loading genotype matrix
 * that does the select/insert based on mode logic.
 *
 * @param $record_type
 *   A human-readable term for your record for error messages.
 * @param $table
 *   The chado table to select/insert from/into.
 * @param $mode
 *   One of 0: Select Only, 1: Insert Only, 2: Insert & Select.
 * @param $select_values
 *   An array of [table column] => [value] mappings. These will be used for both the
 *   select and the insert.
 * @param $insert_values
 *   An array of [table column] => [value] mappings that is specific to the insert.
 * @param $file_name
 *   An optional name for the file to write the values to if mode = 1.
 * @return
 *   The value of the primary key for the inserted/selected record or FALSE if failed.
 */
function genotypes_loader_helper_add_record_with_mode($record_type, $table, $mode, $select_values, $insert_values = array(), $file_name = NULL) {
  
  // The number of records per COPY event.
  $num_per_copy = 50000;
  
  // the name of the primary key.
  $pkey = $table . '_id';

  // If this record should be inserted only then it is safe to save it to a file and load in bulk.
  if ($mode === 1) {

    // If we weren't given the name of the file to write to
    // then we need to determine a file name in a repeatable but unique manner.
    if ($file_name === NULL) {
      $file_stub = '/tmp/genotype_loader.';
      $file_name = $file_stub . $table . '.csv';
    }
    
    // Now open the file to write to since this is needed by fputcsv.
    // @todo I'm concerned this might be a point of slowness. Perhaps there is a better
    //       way to create CSV that doesn't require fputcsv and is more reliable
    //       then simply imploding the values with comma's in-between.
    $file_handle = fopen($file_name, 'w');
    
    // Then we need to write the values to the file.
    $values = array_merge($select_values, $insert_values);
    ksort($values); // to ensure they're always in the same order.
    fputcsv($file_handle, $values);
    
    // Next we need to check if the file is ready to be loaded.
    // @todo concerned this might slow things down drastically. Perhaps consider using
    //        &$num_lines variable in the function definition and keeping track of it
    //        outside the helper function. This is a good fallback though.
    $num_lines = intval(exec("wc -l '$file'"));
    if ($num_lines >= $num_per_copy) {
        
        // Determine the COPY Command using the keys of the values array (i.e. the fields)
        // and the file name.
        $copy_command = 'COPY chado.' . $table . ' ('. implode(',', array_keys($values) . ") FROM '$file_name' WITH CSV";
        
        // Use drush to determine the connection details and then execute the command.
        $connection_string = `drush sql-connect`;
        $connection_string = trim($connection_string);
        $command = $connection_string . ' -c "\\' . $copy_command . '"';
        `$command`;
    }
  }
  // Otherwise, mode = 0 (select only) or 2 (select & insert if missing)
  else {
  
    // Both of the remaining nodes need us to select the record.
    $record = chado_select_record($table, array($pkey), $select_values);
    
    // If it exists and then we can just return the primary key :-).
    if (sizeof($record) == 1) {
      return $record[0]->{$pkey};
    }
    // If there is more then one record then we don't know which one to return.
    // This means we have to report an error :-(.
    } elseif (sizeof($record) > 1) {
      return drush_set_error(dt('Record "@record_type" is not unique. (mode=@mode). Values: ', array('@record_type' => $record_type, '@mode' => $mode)).print_r($values,TRUE));
    }
    // Otherwise, if the mode is 2 (select & insert if missing) then we can insert the record.
    elseif ($mode === 2) {
    
      // Merge the select & insert values so we have all the information we need to insert.
      $values = array_merge($select_values, $insert_values);
      
      // Then insert it :-).
      $record = chado_insert_record($table, $values);
      
      // If the primary key is available then the insert worked and we can return it.
      if (isset($record[$pkey])) {
        return $record[$pkey];
      } 
      // Otherwise, we don't know what went wrong but we should tell the user!
      else {
        return drush_set_error(dt('Tried to insert "@record_type" but the primary key was not available afterwards (mode=@mode). Values: ', array('@record_type' => $record_type, '@mode' => $mode)).print_r($values,TRUE));
      }
    }
  }
}
```

**Comment by carolyncaron** [comment]
I'm currently in the process of testing out this function, and here are the list of hurdles I'm currently experiencing:
- `fopen($file_name, 'w')` wipes the file clean, which means it empties the file before printing every line. Instead I can use 'a' for append, but I need to ensure that I empty the file whenever I reach the desired copy number.
- The default file name created is not unique enough - samples and germplasm end up sharing a file and variants and markers share another file. I could use $record_type in the file name to ensure it is unique but in some cases there will be whitespace, which is not ideal. Perhaps it would be better to require the file_name parameter given to the function.
- The if block for insert only mode does not return anything, meaning an error is thrown because the record wasn't found or successfully inserted. I'm not sure how to handle this, but I have two ideas that would require some design changes throughout the entire module:
  1. Waaayyy back we discussed implementing different error codes, and this could be a case of returning a code that is then ignored by the function that called it. 
  2. I could reserve this helper function for when mode is select only or insert & select, and create a new function specifically for insert only.
  3. Bonus 3rd option that just occurred to me - I could just return TRUE and that would be dead easy. Tested it and it works. Feels like I should think about implementing one of the above two options at some point though (probably the first one)....

Any feedback appreciated 🤗
