### ISSUE TITLE
Loading Somatic data

### ISSUE THREAD

**Issue by Xaiku** [UofS-Pulse-Binfo/vcf_genotypes#53]
Hi everybody,

Can I use genotypes loader to load somatic data?

Here is a screenshot of the file I want to load in.
![image](https://user-images.githubusercontent.com/73877812/116521979-ec8b0900-a8d4-11eb-9625-bbd7f1360cd3.png)

**Comment by carolyncaron** [comment]
Hello Xaiku,

Did you find out a solution to your question? I would say that the loader should work as long as the pipeline used generates data in true VCF format. From your screenshot, I don't think there should be any issue with loading it! If you run into any problems doing so, please don't hesitate to reach out again. :)

**Comment by Xaiku** [comment]
Hey @carolyncaron,

I haven't found a solution yet. I was looking at the documentation again and it says that I need germplasm name + germplasm accession.
![image](https://user-images.githubusercontent.com/73877812/116917499-06b74500-ac4f-11eb-978a-5d05787e6bcf.png)
So I thought that I couldn't use genotypes loader for my somatic vcf file. That's why I closed this issue. But if I do use genotypes loader, do I just not fill in the germplasm name + accession or do I change it to somatic name + accession?

**Comment by carolyncaron** [comment]
I haven't worked with somatic variation data personally, and admittedly the term "germplasm" may be too plant-breeding specific which is my background. I'll consider adding to the documentation to be more inclusive, since the loader should be able to handle any data that is appropriate for Chado.

If I understand somatic data variation correctly, the data is extracted from a particular individual, and there is also a "healthy" sample from the same individual to compare with for non-heritable mutations. Is this the case for your data? If so, I would personally go with a short but descriptive sample name (mine are typically 4-5 words long) having to do with the perceived mutation that you're looking for, and your Germplasm name and accession would reflect the patient or individual. This way, if you choose to also load in the "healthy" sample, you can use the same Germplasm name and accession in your samples file and they will be connected within Chado (but still distinguished using the Sample fields). Think of it as the sample being what is in a particular test tube of genetic material, but germplasm is a particular individual which can be genotyped over and over again. Each time DNA is extracted is a new sample of the genetic material.

Note that you may have the Germplasm/Individual name already in your Chado stock table, in which case you'll want to match the name and accession exactly to keep the loader from creating those records for you. If you are loading this information for the first time, it might be good idea to get in touch with the community that deals with the same type of biological data and see if any standards for entering it into a database might already be suggested.

I hope this helps to clarify things, please let me know if you need any further information!

**Comment by Xaiku** [comment]
Thank you very much!
